# Generated by Django 3.2.9 on 2022-02-21 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('members', '0003_alter_member_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'カテゴリー',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('urgent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=100)),
                ('inquery', models.CharField(max_length=1000)),
                ('respond', models.CharField(max_length=1000)),
                ('contact_name', models.CharField(default='Staff', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('escalated', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_name', to='tickets.category')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.member')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.store')),
            ],
            options={
                'verbose_name_plural': 'チケット',
            },
        ),
    ]
