# Generated by Django 3.2.9 on 2022-03-04 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=100)),
                ('suite', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('zip', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'オフィス',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=60)),
                ('phone', models.IntegerField()),
                ('status', models.CharField(choices=[('Employed', 'Employed'), ('Unemployed', 'Unemployed')], default='Active', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.office')),
            ],
            options={
                'verbose_name_plural': 'スタッフ',
            },
        ),
    ]
