# Generated by Django 3.2.9 on 2022-03-11 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='office',
        ),
    ]
