# Generated by Django 3.2.9 on 2022-03-12 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_member_office'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name_plural': 'スタッフ'},
        ),
    ]
