# Generated by Django 3.2.9 on 2022-03-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
